modify github action

diff --git a/.github/workflows/actions-slack.yml b/.github/workflows/actions-slack.yml
--- a/.github/workflows/actions-slack.yml
+++ b/.github/workflows/actions-slack.yml
@@ -14,7 +14,7 @@ jobs:
     - uses: actions/checkout@v2
 
     - name: Success
-      run: echo 'success' || exit 0
+      run: echo 'success'
 
     - name: Notify success
       if: always()
@@ -26,7 +26,7 @@ jobs:
         cancelled_text: 'Step Cancelled ⚠️' # Optional
 
     - name: Fail
-      run: echo 'fail' || exit 1
+      run: echo 'fail' && exit 1
 
     - name: Notify failure
       if: always()
@@ -38,7 +38,7 @@ jobs:
         cancelled_text: 'Step Cancelled ⚠️' # Optional
 
     - name: Wait a moment
-      run: echo -n 'wait a moment, you can cancel job.'; for ((I=0; I < 60; I++)); do echo -n '.'; done; echo ''
+      run: echo -n 'wait a moment, you can cancel job.'; for ((I=0; I < 60; I++)); do echo -n '.'; sleep 1; done; echo ''
   
     - name: Notify result
       if: always()
